# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('steps', models.IntegerField()),
                ('active_time', models.DurationField()),
                ('when_to_sleep', models.DateTimeField()),
                ('when_to_wake', models.DateTimeField()),
                ('sleep_quality', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
                ('completed_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('estimated_duration', models.DurationField()),
                ('loop_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TagAndSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gtd.ScheduleItem')),
                ('tag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gtd.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagAndTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gtd.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100)),
                ('done_flag', models.BooleanField()),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField()),
                ('due_time', models.DateTimeField()),
                ('estimated_pomodoroes', models.IntegerField()),
                ('current_pomodores', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('work_time', models.IntegerField(default=25)),
                ('short_break_time', models.IntegerField(default=5)),
                ('long_break_time', models.IntegerField(default=15)),
                ('how_many_a_break', models.IntegerField(default=4)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gtd.User'),
        ),
        migrations.AddField(
            model_name='tagandtodo',
            name='todo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gtd.TodoItem'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gtd.User'),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtd.TodoItem'),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gtd.User'),
        ),
        migrations.AlterUniqueTogether(
            name='todoitem',
            unique_together=set([('user', 'todo')]),
        ),
        migrations.AlterUniqueTogether(
            name='tagandtodo',
            unique_together=set([('tag', 'todo')]),
        ),
        migrations.AlterUniqueTogether(
            name='tagandschedule',
            unique_together=set([('tag', 'routine')]),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleitem',
            unique_together=set([('user', 'routine')]),
        ),
    ]
