# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodoro',
            name='end_time',
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
