# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-12 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0002_auto_20161210_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodoro',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='how_many_a_break',
        ),
        migrations.RemoveField(
            model_name='user',
            name='long_break_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='short_break_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_time',
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='duration',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='completed_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
    ]
