# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-14 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0004_auto_20161213_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='loop_types',
            field=models.CharField(choices=[('N', '不循环'), ('D', '每天'), ('W', '每周'), ('M', '每月'), ('Y', '每年')], default='N', max_length=1),
        ),
    ]
