# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0006_remove_todoitem_current_pomodores'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='description',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
